#ifndef DEADLOCK_EXAMPLE_GENERAL_INCLUDED
#define DEADLOCK_EXAMPLE_GENERAL_INCLUDED

#define _UNICODE
#define UNICODE

#define _WINSOCKAPI_ // windows.hを定義した際に、winsock.hを自動的にインクルードしない

#endif DEADLOCK_EXAMPLE_GENERAL_INCLUDED